name: Daily MacBook Air Crawler

on:
  schedule:
    - cron: '0 2 * * *'  # 每天台灣早上 10 點（UTC+8）
    - cron: '0 9 * * *'  # 每天台灣下午 5 點（UTC+8）
  workflow_dispatch:

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run crawler
        env:
          LINE_CHANNEL_TOKEN: ${{ secrets.LINE_CHANNEL_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: python crawler.py
