name: Daily MacBook Air Crawler

on:
  schedule:
    - cron: '50 4 * * *'  # 台灣中午 12:50（UTC+8 -> UTC 04:50）
    - cron: '55 4 * * *'  # 台灣中午 12:45（UTC+8 -> UTC 04:45）
  workflow_dispatch:

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run crawler
        env:
          LINE_CHANNEL_TOKEN: ${{ secrets.LINE_CHANNEL_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: python crawler.py
